services:
  # Database for testing
  auth-service-pg-test-container:
    image: postgres:13
    container_name: auth-service-pg-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_service_test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - auth-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d auth_service_test"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  pgdata_test:

networks:
  auth-test-network:
    driver: bridge
